apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    env: test
spec:
  nodeSelector:
    project: "roboshop"
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent