apiVersion: v1
kind: ConfigMap
metadata:
  name: ann-app
data:
  app.py: |
    from kubernetes import client, config
    import os

    # Load in-cluster config
    config.load_incluster_config()

    # Get pod info from env
    namespace = open("/var/run/secrets/kubernetes.io/serviceaccount/namespace").read()
    pod_name = os.environ["HOSTNAME"]

    v1 = client.CoreV1Api()
    pod = v1.read_namespaced_pod(pod_name, namespace)

    port = pod.metadata.annotations.get("app/port", "80")
    print(f"Starting app on port {port}")
---
apiVersion: v1
kind: Pod
metadata:
  name: ann-reader
  annotations:
    app/port: "8090"
spec:
  serviceAccountName: default
  containers:
    - name: app
      image: python:3.11-slim
      command:
        - sh
        - -c
        - |
          pip install kubernetes && python /app/app.py
      volumeMounts:
        - mountPath: /app
          name: app-code
  volumes:
    - name: app-code
      configMap:
        name: ann-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
