apiVersion: v1
kind: Pod
metadata:
  name: pod-resources-demo
  namespace: pod-resources-example
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "0.5"
          memory: "7000Mi"
        requests:
          cpu: "0.5"
          memory: "7000Mi"
